### ISSUE TITLE
Fix FIPS compliance issues for KubeRay Operator

### ISSUE THREAD

**Issue by anishasthana** [red-hat-data-services/codeflare-operator#5]
We have the following FIPs compliance issues with the KubeRay Operator image

```
openssl library not present  | 
 /manager        | go binary is not CGO_ENABLED | 
```

We should resolve this via PRs to upstream first, if possible.

**Comment by anishasthana** [comment]
hmm, it's not letting me assign @tedhtchang to the issue.
He has a wip branch up at https://github.com/tedhtchang/kuberay/blob/fips/ray-operator/Dockerfile

**Comment by tedhtchang** [comment]
With the wip  this is this scan result:
root@brinks1:~/check-payload# ./check-payload scan operator --spec quay.io/tedchang/kuberay-operator:latest
I1103 17:14:35.367067  373643 validations.go:363] rpm -qf error: exec: "rpm": executable file not found in $PATH (stderr=)
I1103 17:14:35.367176  373643 scan.go:325] "scanning failed" image="quay.io/tedchang/kuberay-operator:latest" path="/usr/sbin/ldconfig" error="executable is not dynamically linked" component="ubi8-minimal-container" tag="" rpm="" status="failed"
---- Failure Report
+------------------------+--------------------+--------------------------------------+------------------------------------------+
| OPERATOR NAME          | EXECUTABLE NAME    | STATUS                               | IMAGE                                    |
+------------------------+--------------------+--------------------------------------+------------------------------------------+
| ubi8-minimal-container | /usr/sbin/ldconfig | executable is not dynamically linked | quay.io/tedchang/kuberay-operator:latest |
+------------------------+--------------------+--------------------------------------+------------------------------------------+
F1103 17:14:35.580738  373643 main.go:259] Error: run failed

 I don't think the test should be marked Error: run failed 
The [config.toml ](https://github.com/openshift/check-payload/blob/c31f01aa12684648d44c976f174a5bf05999a449/config.toml#L35-L38) has 
```
[[rpm.glibc.ignore]]
error = "ErrNotDynLinked"
files = [ "/usr/sbin/ldconfig", "/sbin/ldconfig" ]
```
so I think this error should be ignored.

**Comment by anishasthana** [comment]
Upstream issue: https://github.com/ray-project/kuberay/issues/1632
Upstream PR: https://github.com/ray-project/kuberay/pull/1633

**Comment by tedhtchang** [comment]
Ubuntu is not supported by the payload check program. The error was resolved by testing from a RHEL VM.

**Comment by anishasthana** [comment]
Upstream PR was merged in.
